Change Jupyter them

In [2]:
!jt -t chesterish

Intall tensorflow

In [3]:
!pip install tensorflow

Imported modules for data exploration, manipulation, and model building.

In [4]:
import numpy as np
import pandas as pd
import os
from tqdm.notebook import tqdm_notebook as tqdm
from sklearn.model_selection import train_test_split
import tensorflow as tf
from keras.models import Sequential, Model
from keras.utils import to_categorical
from keras.layers import RepeatVector, Input, Dense, Flatten, AveragePooling2D, Dropout
from keras.applications.vgg16 import VGG16, decode_predictions, preprocess_input
from keras.applications.mobilenet import MobileNet, decode_predictions, preprocess_input
from keras.applications.densenet import DenseNet121, decode_predictions, preprocess_input
from keras.applications.efficientnet import EfficientNetB0, decode_predictions, preprocess_input

Mounted my google drive for ease of access to dog images (If not on jupyter notebook).

In [5]:
#drive.mount('/content/gdrive')

Created variables for training training data, testing data, and labels.

In [6]:
data = 'train'
test = 'test'
labels = 'labels.csv'

Reading the labels in the labels.csv file and adding a column for the path of each image in the training dataset.

In [7]:
labels_csv = pd.read_csv('labels.csv')
labels_csv["path"] = 'train/'+ labels_csv["id"]+".jpg"
labels_csv.head(30)

id                    breed  \
0   000bec180eb18c7604dcecc8fe0dba07              boston_bull   
1   001513dfcb2ffafc82cccf4d8bbaba97                    dingo   
2   001cdf01b096e06d78e9e5112d419397                 pekinese   
3   00214f311d5d2247d5dfe4fe24b2303d                 bluetick   
4   0021f9ceb3235effd7fcde7f7538ed62         golden_retriever   
5   002211c81b498ef88e1b40b9abf84e1d       bedlington_terrier   
6   00290d3e1fdd27226ba27a8ce248ce85       bedlington_terrier   
7   002a283a315af96eaea0e28e7163b21b                   borzoi   
8   003df8b8a8b05244b1d920bb6cf451f9                  basenji   
9   0042188c895a2f14ef64a918ed9c7b64       scottish_deerhound   
10  004396df1acd0f1247b740ca2b14616e        shetland_sheepdog   
11  0067dc3eab0b3c3ef0439477624d85d6             walker_hound   
12  00693b8bc2470375cc744a6391d397ec              maltese_dog   
13  006cc3ddb9dc1bd827479569fcdc52dc                 bluetick   
14  0075dc49dab4024d12fafe67074d8a81          norfolk_terrier   
15  00792e341f3c6eb33663e415d0715370      african_hunting_dog   
16  007b5a16db9d9ff9d7ad39982703e429  wire-haired_fox_terrier   
17  007b8a07882822475a4ce6581e70b1f8                  redbone   
18  007ff9a78eba2aebb558afea3a51c469         lakeland_terrier   
19  008887054b18ba3c7601792b6a453cc3                    boxer   
20  008b1271ed1addaccf93783b39deab45                 doberman   
21  008ba178d6dfc1a583617470d19c1673               otterhound   
22  009509be3ca7cce0ff9e37c8b09b1125               otterhound   
23  0097c6242c6f3071762d9f85c3ef1b2f       bedlington_terrier   
24  00a338a92e4e7bf543340dc849230e75                    dingo   
25  00a366d4b4a9bbb6c8a63126697b7656         golden_retriever   
26  00a862390341c5be090dd72bd2bc19ef       standard_schnauzer   
27  00b7d114bc5166a629a3cc03d9329120      irish_water_spaniel   
28  00ba244566e36e0af3d979320fd3017f  black-and-tan_coonhound   
29  00bee065dcec471f26394855c5c2f3de                    cairn   

                                          path  
0   train/000bec180eb18c7604dcecc8fe0dba07.jpg  
1   train/001513dfcb2ffafc82cccf4d8bbaba97.jpg  
2   train/001cdf01b096e06d78e9e5112d419397.jpg  
3   train/00214f311d5d2247d5dfe4fe24b2303d.jpg  
4   train/0021f9ceb3235effd7fcde7f7538ed62.jpg  
5   train/002211c81b498ef88e1b40b9abf84e1d.jpg  
6   train/00290d3e1fdd27226ba27a8ce248ce85.jpg  
7   train/002a283a315af96eaea0e28e7163b21b.jpg  
8   train/003df8b8a8b05244b1d920bb6cf451f9.jpg  
9   train/0042188c895a2f14ef64a918ed9c7b64.jpg  
10  train/004396df1acd0f1247b740ca2b14616e.jpg  
11  train/0067dc3eab0b3c3ef0439477624d85d6.jpg  
12  train/00693b8bc2470375cc744a6391d397ec.jpg  
13  train/006cc3ddb9dc1bd827479569fcdc52dc.jpg  
14  train/0075dc49dab4024d12fafe67074d8a81.jpg  
15  train/00792e341f3c6eb33663e415d0715370.jpg  
16  train/007b5a16db9d9ff9d7ad39982703e429.jpg  
17  train/007b8a07882822475a4ce6581e70b1f8.jpg  
18  train/007ff9a78eba2aebb558afea3a51c469.jpg  
19  train/008887054b18ba3c7601792b6a453cc3.jpg  
20  train/008b1271ed1addaccf93783b39deab45.jpg  
21  train/008ba178d6dfc1a583617470d19c1673.jpg  
22  train/009509be3ca7cce0ff9e37c8b09b1125.jpg  
23  train/0097c6242c6f3071762d9f85c3ef1b2f.jpg  
24  train/00a338a92e4e7bf543340dc849230e75.jpg  
25  train/00a366d4b4a9bbb6c8a63126697b7656.jpg  
26  train/00a862390341c5be090dd72bd2bc19ef.jpg  
27  train/00b7d114bc5166a629a3cc03d9329120.jpg  
28  train/00ba244566e36e0af3d979320fd3017f.jpg  
29  train/00bee065dcec471f26394855c5c2f3de.jpg

Explored the number of unique breeds in the dataset.

In [8]:
print(len(labels_csv['breed'].unique()))

120


1. Create an empty array that matches the shape of the data.
2. Iterate through each index/image in the labels.csv file.
3. Each iteration follows this process.
*   Load image.
*   Convert the image to an array.
*   Normalize and scale the pixels in the pre-processing process.
*   Convert the image array to a batch of arrays to be easily processed by the network - each model has a pre-processing method.
*   Store the array in the empty array created earlier.

In [9]:
x_labels_vgg = np.zeros((labels_csv.shape[0], 128, 128, 3), dtype=np.float32)
x_labels_mobile = np.zeros((labels_csv.shape[0], 128, 128, 3), dtype=np.float32)
x_labels_dense = np.zeros((labels_csv.shape[0], 128, 128, 3), dtype=np.float32)
x_labels_eff = np.zeros((labels_csv.shape[0], 128, 128, 3), dtype=np.float32)

for i, index in tqdm(enumerate(labels_csv['path'])):
    image = tf.keras.preprocessing.image.load_img(index, target_size=(128,128))

    img_array = tf.keras.preprocessing.image.img_to_array(image)

    img_array_vgg = tf.keras.applications.vgg16.preprocess_input(img_array)
    img_array_vgg = np.expand_dims(img_array_vgg, axis=0)
    x_labels_vgg[i] = img_array_vgg

    img_array_mobile = tf.keras.applications.mobilenet.preprocess_input(img_array)
    img_array_mobile = np.expand_dims(img_array_mobile, axis=0)
    x_labels_mobile[i] = img_array_mobile

    img_array_dense = tf.keras.applications.densenet.preprocess_input(img_array)
    img_array_dense = np.expand_dims(img_array_dense, axis=0)
    x_labels_dense[i] = img_array_dense
    
    img_array_eff = tf.keras.applications.efficientnet.preprocess_input(img_array)
    img_array_eff = np.expand_dims(img_array_eff, axis=0)
    x_labels_eff[i] = img_array_eff

0it [00:00, ?it/s]

One-hot encode the classes, in this case the dog breeds.

In [10]:
labels_csv.breed = pd.Categorical(pd.factorize(labels_csv.breed)[0])
y_labels = to_categorical(labels_csv["breed"],num_classes=120)
print(y_labels)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


View the shape of x and y labels

In [11]:
print(x_labels_vgg.shape)
print(y_labels.shape)

(10222, 128, 128, 3)
(10222, 120)


View encoding.

In [12]:
print(x_labels_vgg)

[[[[-2.8939003e+01  4.2210007e+00  5.5320000e+01]
   [-8.0939003e+01 -4.1778999e+01 -2.6800003e+00]
   [ 1.5060997e+01  6.5221001e+01  9.6320000e+01]
   ...
   [ 3.0060997e+01  8.6221001e+01  1.1232000e+02]
   [-2.6939003e+01  7.8221001e+01  9.6320000e+01]
   [-4.1939003e+01  2.2221001e+01  4.7320000e+01]]

  [[-6.5939003e+01 -4.6778999e+01 -1.2680000e+01]
   [ 1.9060997e+01  4.3221001e+01  7.0320000e+01]
   [ 2.8060997e+01  5.6221001e+01  8.2320000e+01]
   ...
   [-3.3939003e+01  1.8221001e+01  5.5320000e+01]
   [ 6.0609970e+00  7.7221001e+01  1.0532000e+02]
   [-3.0939003e+01  6.0221001e+01  8.8320000e+01]]

  [[-5.1939003e+01 -2.1778999e+01  1.4320000e+01]
   [-3.1939003e+01  2.2100067e-01  3.7320000e+01]
   [-4.1939003e+01 -1.2778999e+01  2.7320000e+01]
   ...
   [-7.1939003e+01 -7.7899933e-01  4.4320000e+01]
   [-2.7939003e+01  3.0221001e+01  6.1320000e+01]
   [-3.3939003e+01  5.8221001e+01  9.2320000e+01]]

  ...

  [[-1.7939003e+01  2.2210007e+00  6.8320000e+01]
   [-3.8939003e+

View encoding.

In [13]:
print(y_labels)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


Split the data into training and testing for each model.

In [14]:
X_train, X_test, y_train, y_test = train_test_split(x_labels_vgg, y_labels, test_size = 0.2, random_state=2)
X_train1, X_test1, y_train1, y_test1 = train_test_split(x_labels_mobile, y_labels, test_size = 0.2, random_state=2)
X_train2, X_test2, y_train2, y_test2 = train_test_split(x_labels_dense, y_labels, test_size = 0.2, random_state=2)
X_train3, X_test3, y_train3, y_test = train_test_split(x_labels_eff, y_labels, test_size = 0.2, random_state=2)

.Vew the first set of x arrays

In [15]:
print(X_train)

[[[[ -71.939       -76.779       -90.68      ]
   [ -78.939       -84.779       -96.68      ]
   [ -84.939       -90.779      -100.68      ]
   ...
   [ -76.939       -88.779       -81.68      ]
   [ -83.939       -96.779       -91.68      ]
   [ -79.939       -93.779       -90.68      ]]

  [[ -42.939003    -47.779       -64.68      ]
   [ -43.939003    -49.779       -63.68      ]
   [ -30.939003    -37.779       -49.68      ]
   ...
   [ -86.939       -96.779       -89.68      ]
   [ -81.939       -91.779       -84.68      ]
   [ -79.939       -90.779       -86.68      ]]

  [[  31.060997     20.221         7.3199997 ]
   [  40.060997     29.221        16.32      ]
   [  30.060997     18.221         7.3199997 ]
   ...
   [ -82.939       -86.779       -79.68      ]
   [ -89.939       -94.779       -88.68      ]
   [ -88.939       -95.779       -91.68      ]]

  ...

  [[ -98.939      -102.779      -112.68      ]
   [ -98.939      -109.779       -98.68      ]
   [ -98.939      -111.779

View the one-hot encoded y labels.

In [16]:
print(y_train)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


Create an earlystopping object for all models. This method stops training the model if the accuracy stays consistent for two iterations.

In [17]:
earlystop = tf.keras.callbacks.EarlyStopping(monitor='accuracy', patience=2)

VGG16 model creation with an extra pooling layer, flatten layer, and dense layer.

In [18]:
m1=tf.keras.applications.vgg16.VGG16(weights= 'imagenet',include_top=False, input_shape=(128, 128, 3))
m1.trainable = False

x = m1.output
x = AveragePooling2D()(x)
x = Flatten()(x)
x = Dropout(.2)(x)
x = Dense(120, activation='softmax')(x)
m1_model = Model(inputs=m1.input, outputs=x)
m1_model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 128, 128, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 128, 128, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 128, 128, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 64, 64, 64)        0         
                                                                 
 block2_conv1 (Conv2D)       (None, 64, 64, 128)       73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 64, 64, 128)       147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 32, 32, 128)       0     

In [19]:
m1_model.compile(optimizer='adam',loss="categorical_crossentropy",metrics=["accuracy"])

In [20]:
m1_model.fit(X_train, y_train, epochs=20, batch_size=32, callbacks=[earlystop], validation_data = (X_test, y_test))

Epoch 1/20
256/256 [==============================] - 437s 2s/step - loss: 28.3049 - accuracy: 0.1696 - val_loss: 16.7041 - val_accuracy: 0.3193
Epoch 2/20
256/256 [==============================] - 430s 2s/step - loss: 11.3446 - accuracy: 0.4586 - val_loss: 15.7506 - val_accuracy: 0.3682
Epoch 3/20
256/256 [==============================] - 387s 2s/step - loss: 6.4634 - accuracy: 0.6167 - val_loss: 16.0906 - val_accuracy: 0.3902
Epoch 4/20
256/256 [==============================] - 403s 2s/step - loss: 4.2042 - accuracy: 0.7069 - val_loss: 16.8168 - val_accuracy: 0.3995
Epoch 5/20
256/256 [==============================] - 375s 1s/step - loss: 3.2029 - accuracy: 0.7642 - val_loss: 17.1240 - val_accuracy: 0.3936
Epoch 6/20
256/256 [==============================] - 397s 2s/step - loss: 2.4590 - accuracy: 0.8104 - val_loss: 17.4172 - val_accuracy: 0.4039
Epoch 7/20
256/256 [==============================] - 416s 2s/step - loss: 1.9330 - accuracy: 0.8433 - val_loss: 17.9900 - val_accurac

MobileNet model creation with an extra pooling layer, flatten layer, and dense layer.

In [21]:
m2=tf.keras.applications.mobilenet.MobileNet(weights= 'imagenet',include_top=False, input_shape=(128, 128, 3))
m2.trainable = False

x = m2.output
x = AveragePooling2D()(x)
x = Flatten()(x)
x = Dropout(.2)(x)
x = Dense(120, activation='softmax')(x)
m2_model = Model(inputs=m2.input, outputs=x)
m2_model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 128, 128, 3)]     0         
                                                                 
 conv1 (Conv2D)              (None, 64, 64, 32)        864       
                                                                 
 conv1_bn (BatchNormalizatio  (None, 64, 64, 32)       128       
 n)                                                              
                                                                 
 conv1_relu (ReLU)           (None, 64, 64, 32)        0         
                                                                 
 conv_dw_1 (DepthwiseConv2D)  (None, 64, 64, 32)       288       
                                                                 
 conv_dw_1_bn (BatchNormaliz  (None, 64, 64, 32)       128       
 ation)                                                    

                                                                 
 conv_pw_8_bn (BatchNormaliz  (None, 8, 8, 512)        2048      
 ation)                                                          
                                                                 
 conv_pw_8_relu (ReLU)       (None, 8, 8, 512)         0         
                                                                 
 conv_dw_9 (DepthwiseConv2D)  (None, 8, 8, 512)        4608      
                                                                 
 conv_dw_9_bn (BatchNormaliz  (None, 8, 8, 512)        2048      
 ation)                                                          
                                                                 
 conv_dw_9_relu (ReLU)       (None, 8, 8, 512)         0         
                                                                 
 conv_pw_9 (Conv2D)          (None, 8, 8, 512)         262144    
                                                                 
 conv_pw_9

In [22]:
m2_model.compile(optimizer='adam',loss="categorical_crossentropy",metrics=["accuracy"])

In [23]:
m2_model.fit(X_train, y_train, epochs=20, batch_size=32,callbacks=[earlystop], validation_data = (X_test, y_test))

Epoch 1/20
256/256 [==============================] - 66s 246ms/step - loss: 5.7322 - accuracy: 0.0781 - val_loss: 4.9091 - val_accuracy: 0.1193
Epoch 2/20
256/256 [==============================] - 60s 235ms/step - loss: 2.2628 - accuracy: 0.4554 - val_loss: 4.9416 - val_accuracy: 0.1374
Epoch 3/20
256/256 [==============================] - 59s 230ms/step - loss: 1.0486 - accuracy: 0.7096 - val_loss: 5.0365 - val_accuracy: 0.1384
Epoch 4/20
256/256 [==============================] - 58s 226ms/step - loss: 0.4989 - accuracy: 0.8660 - val_loss: 5.1575 - val_accuracy: 0.1399
Epoch 5/20
256/256 [==============================] - 59s 230ms/step - loss: 0.2684 - accuracy: 0.9324 - val_loss: 5.1541 - val_accuracy: 0.1526
Epoch 6/20
256/256 [==============================] - 57s 223ms/step - loss: 0.1738 - accuracy: 0.9617 - val_loss: 5.3027 - val_accuracy: 0.1535
Epoch 7/20
256/256 [==============================] - 57s 222ms/step - loss: 0.1449 - accuracy: 0.9695 - val_loss: 5.4171 - val_ac

DenseNet model creation with an extra pooling layer, flatten layer, and dense layer.

In [24]:
m3=tf.keras.applications.densenet.DenseNet121(weights='imagenet',include_top=False, input_shape=(128, 128, 3))
m3.trainable = False

x = m3.output
x = AveragePooling2D()(x)
x = Flatten()(x)
x = Dropout(.2)(x)
x = Dense(120, activation='softmax')(x)
m3_model = Model(inputs=m3.input, outputs=x)
m3_model.summary()

Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_3 (InputLayer)           [(None, 128, 128, 3  0           []                               
                                )]                                                                
                                                                                                  
 zero_padding2d (ZeroPadding2D)  (None, 134, 134, 3)  0          ['input_3[0][0]']                
                                                                                                  
 conv1/conv (Conv2D)            (None, 64, 64, 64)   9408        ['zero_padding2d[0][0]']         
                                                                                                  
 conv1/bn (BatchNormalization)  (None, 64, 64, 64)   256         ['conv1/conv[0][0]']       

                                                                                                  
 conv2_block4_1_bn (BatchNormal  (None, 32, 32, 128)  512        ['conv2_block4_1_conv[0][0]']    
 ization)                                                                                         
                                                                                                  
 conv2_block4_1_relu (Activatio  (None, 32, 32, 128)  0          ['conv2_block4_1_bn[0][0]']      
 n)                                                                                               
                                                                                                  
 conv2_block4_2_conv (Conv2D)   (None, 32, 32, 32)   36864       ['conv2_block4_1_relu[0][0]']    
                                                                                                  
 conv2_block4_concat (Concatena  (None, 32, 32, 192)  0          ['conv2_block3_concat[0][0]',    
 te)      

 conv3_block2_1_conv (Conv2D)   (None, 16, 16, 128)  20480       ['conv3_block2_0_relu[0][0]']    
                                                                                                  
 conv3_block2_1_bn (BatchNormal  (None, 16, 16, 128)  512        ['conv3_block2_1_conv[0][0]']    
 ization)                                                                                         
                                                                                                  
 conv3_block2_1_relu (Activatio  (None, 16, 16, 128)  0          ['conv3_block2_1_bn[0][0]']      
 n)                                                                                               
                                                                                                  
 conv3_block2_2_conv (Conv2D)   (None, 16, 16, 32)   36864       ['conv3_block2_1_relu[0][0]']    
                                                                                                  
 conv3_blo

                                                                                                  
 conv3_block6_2_conv (Conv2D)   (None, 16, 16, 32)   36864       ['conv3_block6_1_relu[0][0]']    
                                                                                                  
 conv3_block6_concat (Concatena  (None, 16, 16, 320)  0          ['conv3_block5_concat[0][0]',    
 te)                                                              'conv3_block6_2_conv[0][0]']    
                                                                                                  
 conv3_block7_0_bn (BatchNormal  (None, 16, 16, 320)  1280       ['conv3_block6_concat[0][0]']    
 ization)                                                                                         
                                                                                                  
 conv3_block7_0_relu (Activatio  (None, 16, 16, 320)  0          ['conv3_block7_0_bn[0][0]']      
 n)       

 lization)                                                                                        
                                                                                                  
 conv3_block11_0_relu (Activati  (None, 16, 16, 448)  0          ['conv3_block11_0_bn[0][0]']     
 on)                                                                                              
                                                                                                  
 conv3_block11_1_conv (Conv2D)  (None, 16, 16, 128)  57344       ['conv3_block11_0_relu[0][0]']   
                                                                                                  
 conv3_block11_1_bn (BatchNorma  (None, 16, 16, 128)  512        ['conv3_block11_1_conv[0][0]']   
 lization)                                                                                        
                                                                                                  
 conv3_blo

 conv4_block3_0_bn (BatchNormal  (None, 8, 8, 320)   1280        ['conv4_block2_concat[0][0]']    
 ization)                                                                                         
                                                                                                  
 conv4_block3_0_relu (Activatio  (None, 8, 8, 320)   0           ['conv4_block3_0_bn[0][0]']      
 n)                                                                                               
                                                                                                  
 conv4_block3_1_conv (Conv2D)   (None, 8, 8, 128)    40960       ['conv4_block3_0_relu[0][0]']    
                                                                                                  
 conv4_block3_1_bn (BatchNormal  (None, 8, 8, 128)   512         ['conv4_block3_1_conv[0][0]']    
 ization)                                                                                         
          

                                                                                                  
 conv4_block7_1_bn (BatchNormal  (None, 8, 8, 128)   512         ['conv4_block7_1_conv[0][0]']    
 ization)                                                                                         
                                                                                                  
 conv4_block7_1_relu (Activatio  (None, 8, 8, 128)   0           ['conv4_block7_1_bn[0][0]']      
 n)                                                                                               
                                                                                                  
 conv4_block7_2_conv (Conv2D)   (None, 8, 8, 32)     36864       ['conv4_block7_1_relu[0][0]']    
                                                                                                  
 conv4_block7_concat (Concatena  (None, 8, 8, 480)   0           ['conv4_block6_concat[0][0]',    
 te)      

 conv4_block11_2_conv (Conv2D)  (None, 8, 8, 32)     36864       ['conv4_block11_1_relu[0][0]']   
                                                                                                  
 conv4_block11_concat (Concaten  (None, 8, 8, 608)   0           ['conv4_block10_concat[0][0]',   
 ate)                                                             'conv4_block11_2_conv[0][0]']   
                                                                                                  
 conv4_block12_0_bn (BatchNorma  (None, 8, 8, 608)   2432        ['conv4_block11_concat[0][0]']   
 lization)                                                                                        
                                                                                                  
 conv4_block12_0_relu (Activati  (None, 8, 8, 608)   0           ['conv4_block12_0_bn[0][0]']     
 on)                                                                                              
          

                                                                                                  
 conv4_block16_0_relu (Activati  (None, 8, 8, 736)   0           ['conv4_block16_0_bn[0][0]']     
 on)                                                                                              
                                                                                                  
 conv4_block16_1_conv (Conv2D)  (None, 8, 8, 128)    94208       ['conv4_block16_0_relu[0][0]']   
                                                                                                  
 conv4_block16_1_bn (BatchNorma  (None, 8, 8, 128)   512         ['conv4_block16_1_conv[0][0]']   
 lization)                                                                                        
                                                                                                  
 conv4_block16_1_relu (Activati  (None, 8, 8, 128)   0           ['conv4_block16_1_bn[0][0]']     
 on)      

 lization)                                                                                        
                                                                                                  
 conv4_block20_1_relu (Activati  (None, 8, 8, 128)   0           ['conv4_block20_1_bn[0][0]']     
 on)                                                                                              
                                                                                                  
 conv4_block20_2_conv (Conv2D)  (None, 8, 8, 32)     36864       ['conv4_block20_1_relu[0][0]']   
                                                                                                  
 conv4_block20_concat (Concaten  (None, 8, 8, 896)   0           ['conv4_block19_concat[0][0]',   
 ate)                                                             'conv4_block20_2_conv[0][0]']   
                                                                                                  
 conv4_blo

 conv4_block24_concat (Concaten  (None, 8, 8, 1024)  0           ['conv4_block23_concat[0][0]',   
 ate)                                                             'conv4_block24_2_conv[0][0]']   
                                                                                                  
 pool4_bn (BatchNormalization)  (None, 8, 8, 1024)   4096        ['conv4_block24_concat[0][0]']   
                                                                                                  
 pool4_relu (Activation)        (None, 8, 8, 1024)   0           ['pool4_bn[0][0]']               
                                                                                                  
 pool4_conv (Conv2D)            (None, 8, 8, 512)    524288      ['pool4_relu[0][0]']             
                                                                                                  
 pool4_pool (AveragePooling2D)  (None, 4, 4, 512)    0           ['pool4_conv[0][0]']             
          

                                                                                                  
 conv5_block4_concat (Concatena  (None, 4, 4, 640)   0           ['conv5_block3_concat[0][0]',    
 te)                                                              'conv5_block4_2_conv[0][0]']    
                                                                                                  
 conv5_block5_0_bn (BatchNormal  (None, 4, 4, 640)   2560        ['conv5_block4_concat[0][0]']    
 ization)                                                                                         
                                                                                                  
 conv5_block5_0_relu (Activatio  (None, 4, 4, 640)   0           ['conv5_block5_0_bn[0][0]']      
 n)                                                                                               
                                                                                                  
 conv5_blo

 conv5_block9_0_relu (Activatio  (None, 4, 4, 768)   0           ['conv5_block9_0_bn[0][0]']      
 n)                                                                                               
                                                                                                  
 conv5_block9_1_conv (Conv2D)   (None, 4, 4, 128)    98304       ['conv5_block9_0_relu[0][0]']    
                                                                                                  
 conv5_block9_1_bn (BatchNormal  (None, 4, 4, 128)   512         ['conv5_block9_1_conv[0][0]']    
 ization)                                                                                         
                                                                                                  
 conv5_block9_1_relu (Activatio  (None, 4, 4, 128)   0           ['conv5_block9_1_bn[0][0]']      
 n)                                                                                               
          

                                                                                                  
 conv5_block13_1_relu (Activati  (None, 4, 4, 128)   0           ['conv5_block13_1_bn[0][0]']     
 on)                                                                                              
                                                                                                  
 conv5_block13_2_conv (Conv2D)  (None, 4, 4, 32)     36864       ['conv5_block13_1_relu[0][0]']   
                                                                                                  
 conv5_block13_concat (Concaten  (None, 4, 4, 928)   0           ['conv5_block12_concat[0][0]',   
 ate)                                                             'conv5_block13_2_conv[0][0]']   
                                                                                                  
 conv5_block14_0_bn (BatchNorma  (None, 4, 4, 928)   3712        ['conv5_block13_concat[0][0]']   
 lization)

In [25]:
m3_model.compile(optimizer='adam',loss="categorical_crossentropy",metrics=["accuracy"])

In [26]:
m3_model.fit(X_train, y_train, epochs=20, batch_size=32, callbacks=[earlystop], validation_data = (X_test, y_test))

Epoch 1/20
256/256 [==============================] - 231s 880ms/step - loss: 20.5877 - accuracy: 0.0291 - val_loss: 15.4376 - val_accuracy: 0.0406
Epoch 2/20
256/256 [==============================] - 220s 861ms/step - loss: 14.9473 - accuracy: 0.0846 - val_loss: 18.0870 - val_accuracy: 0.0626
Epoch 3/20
256/256 [==============================] - 221s 865ms/step - loss: 12.1624 - accuracy: 0.1519 - val_loss: 17.4223 - val_accuracy: 0.0533
Epoch 4/20
256/256 [==============================] - 218s 853ms/step - loss: 10.5353 - accuracy: 0.2167 - val_loss: 17.6494 - val_accuracy: 0.0606
Epoch 5/20
256/256 [==============================] - 220s 859ms/step - loss: 9.1472 - accuracy: 0.2656 - val_loss: 18.0834 - val_accuracy: 0.0670
Epoch 6/20
256/256 [==============================] - 220s 858ms/step - loss: 8.0962 - accuracy: 0.3166 - val_loss: 18.8536 - val_accuracy: 0.0631
Epoch 7/20
256/256 [==============================] - 223s 873ms/step - loss: 7.5359 - accuracy: 0.3450 - val_loss

EfficientNet model creation with an extra pooling layer, flatten layer, and dense layer.

In [27]:
m4=tf.keras.applications.efficientnet.EfficientNetB0(weights='imagenet',include_top=False, input_shape=(128, 128, 3))
m4.trainable = False

x = m4.output
x = AveragePooling2D()(x)
x = Flatten()(x)
x = Dropout(.2)(x)
x = Dense(120, activation='softmax')(x)
m4_model = Model(inputs=m4.input, outputs=x)
m4_model.summary()

Model: "model_3"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_4 (InputLayer)           [(None, 128, 128, 3  0           []                               
                                )]                                                                
                                                                                                  
 rescaling (Rescaling)          (None, 128, 128, 3)  0           ['input_4[0][0]']                
                                                                                                  
 normalization (Normalization)  (None, 128, 128, 3)  7           ['rescaling[0][0]']              
                                                                                                  
 rescaling_1 (Rescaling)        (None, 128, 128, 3)  0           ['normalization[0][0]']    

 block2b_expand_conv (Conv2D)   (None, 32, 32, 144)  3456        ['block2a_project_bn[0][0]']     
                                                                                                  
 block2b_expand_bn (BatchNormal  (None, 32, 32, 144)  576        ['block2b_expand_conv[0][0]']    
 ization)                                                                                         
                                                                                                  
 block2b_expand_activation (Act  (None, 32, 32, 144)  0          ['block2b_expand_bn[0][0]']      
 ivation)                                                                                         
                                                                                                  
 block2b_dwconv (DepthwiseConv2  (None, 32, 32, 144)  1296       ['block2b_expand_activation[0][0]
 D)                                                              ']                               
          

                                                                                                  
 block3b_dwconv (DepthwiseConv2  (None, 16, 16, 240)  6000       ['block3b_expand_activation[0][0]
 D)                                                              ']                               
                                                                                                  
 block3b_bn (BatchNormalization  (None, 16, 16, 240)  960        ['block3b_dwconv[0][0]']         
 )                                                                                                
                                                                                                  
 block3b_activation (Activation  (None, 16, 16, 240)  0          ['block3b_bn[0][0]']             
 )                                                                                                
                                                                                                  
 block3b_s

 block4b_activation (Activation  (None, 8, 8, 480)   0           ['block4b_bn[0][0]']             
 )                                                                                                
                                                                                                  
 block4b_se_squeeze (GlobalAver  (None, 480)         0           ['block4b_activation[0][0]']     
 agePooling2D)                                                                                    
                                                                                                  
 block4b_se_reshape (Reshape)   (None, 1, 1, 480)    0           ['block4b_se_squeeze[0][0]']     
                                                                                                  
 block4b_se_reduce (Conv2D)     (None, 1, 1, 20)     9620        ['block4b_se_reshape[0][0]']     
                                                                                                  
 block4b_s

                                                                                                  
 block5a_se_reshape (Reshape)   (None, 1, 1, 480)    0           ['block5a_se_squeeze[0][0]']     
                                                                                                  
 block5a_se_reduce (Conv2D)     (None, 1, 1, 20)     9620        ['block5a_se_reshape[0][0]']     
                                                                                                  
 block5a_se_expand (Conv2D)     (None, 1, 1, 480)    10080       ['block5a_se_reduce[0][0]']      
                                                                                                  
 block5a_se_excite (Multiply)   (None, 8, 8, 480)    0           ['block5a_activation[0][0]',     
                                                                  'block5a_se_expand[0][0]']      
                                                                                                  
 block5a_p

 block5c_project_conv (Conv2D)  (None, 8, 8, 112)    75264       ['block5c_se_excite[0][0]']      
                                                                                                  
 block5c_project_bn (BatchNorma  (None, 8, 8, 112)   448         ['block5c_project_conv[0][0]']   
 lization)                                                                                        
                                                                                                  
 block5c_drop (Dropout)         (None, 8, 8, 112)    0           ['block5c_project_bn[0][0]']     
                                                                                                  
 block5c_add (Add)              (None, 8, 8, 112)    0           ['block5c_drop[0][0]',           
                                                                  'block5b_add[0][0]']            
                                                                                                  
 block6a_e

 block6b_add (Add)              (None, 4, 4, 192)    0           ['block6b_drop[0][0]',           
                                                                  'block6a_project_bn[0][0]']     
                                                                                                  
 block6c_expand_conv (Conv2D)   (None, 4, 4, 1152)   221184      ['block6b_add[0][0]']            
                                                                                                  
 block6c_expand_bn (BatchNormal  (None, 4, 4, 1152)  4608        ['block6c_expand_conv[0][0]']    
 ization)                                                                                         
                                                                                                  
 block6c_expand_activation (Act  (None, 4, 4, 1152)  0           ['block6c_expand_bn[0][0]']      
 ivation)                                                                                         
          

 block7a_expand_bn (BatchNormal  (None, 4, 4, 1152)  4608        ['block7a_expand_conv[0][0]']    
 ization)                                                                                         
                                                                                                  
 block7a_expand_activation (Act  (None, 4, 4, 1152)  0           ['block7a_expand_bn[0][0]']      
 ivation)                                                                                         
                                                                                                  
 block7a_dwconv (DepthwiseConv2  (None, 4, 4, 1152)  10368       ['block7a_expand_activation[0][0]
 D)                                                              ']                               
                                                                                                  
 block7a_bn (BatchNormalization  (None, 4, 4, 1152)  4608        ['block7a_dwconv[0][0]']         
 )        

In [28]:
m4_model.compile(optimizer='adam',loss="categorical_crossentropy",metrics=["accuracy"])

In [29]:
m4_model.fit(X_train, y_train, epochs=20, batch_size=32, callbacks=[earlystop], validation_data = (X_test, y_test))

Epoch 1/20
256/256 [==============================] - 132s 493ms/step - loss: 4.6895 - accuracy: 0.0698 - val_loss: 4.2525 - val_accuracy: 0.1242
Epoch 2/20
256/256 [==============================] - 123s 482ms/step - loss: 2.9189 - accuracy: 0.3174 - val_loss: 4.2859 - val_accuracy: 0.1359
Epoch 3/20
256/256 [==============================] - 124s 484ms/step - loss: 2.1195 - accuracy: 0.5002 - val_loss: 4.4182 - val_accuracy: 0.1311
Epoch 4/20
256/256 [==============================] - 123s 482ms/step - loss: 1.6712 - accuracy: 0.6133 - val_loss: 4.5286 - val_accuracy: 0.1325
Epoch 5/20
256/256 [==============================] - 129s 503ms/step - loss: 1.3647 - accuracy: 0.6901 - val_loss: 4.7122 - val_accuracy: 0.1237
Epoch 6/20
256/256 [==============================] - 133s 519ms/step - loss: 1.1605 - accuracy: 0.7347 - val_loss: 4.7792 - val_accuracy: 0.1301
Epoch 7/20
256/256 [==============================] - 123s 480ms/step - loss: 1.0138 - accuracy: 0.7753 - val_loss: 4.9163 -

Created a process to convert a single image into an array for prediction.

This model uses a similar method to the one above that converts all images in the train file and puts them into an empty array.

In [40]:
x_predict = np.zeros([128, 128, 3], dtype=np.float32)
pred_image = tf.keras.preprocessing.image.load_img('pug.jpg', target_size=(128,128))
pred_img_array = tf.keras.preprocessing.image.img_to_array(pred_image)
pred_img_array = tf.keras.applications.mobilenet.preprocess_input(pred_img_array)
pred_img_array = np.expand_dims(pred_img_array, axis=0)
x_predict = pred_img_array

Predict a single image from the one hot encoded labels.
This method also reverses the onehot encoding to reveal the original class.

In [41]:
prediction = m1_model.predict(x_predict)

1/1 [==============================] - 0s 79ms/step


Get the highest probability using the "argmax" method. The class with the highest probability is pulled from the array of y labels (pred_y_labels).

In [44]:
labels_csv = pd.read_csv('labels.csv')
breed_labels = pd.Categorical(pd.factorize(labels_csv.breed)[0])
pred_y_labels = labels_csv["breed"].unique()

pred = np.argmax(prediction, axis=1)

print(pred_y_labels[pred])

['pug']
